[package]
name = "ximple-common"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
