name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish_crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build setup
        uses: ./.github/actions/build_setup
      - name: Publish the respective crates
        run: cargo publish
